// common/radio_config.h — Shared radio protocol constants for rocket and base station.
// Include this file from both rocket_avionics and base_station.
// Contains everything that must match exactly between the two firmwares.
// Per-device tuning (TX power, NVS keys, BLE config) stays in the respective config.h.

#ifndef COMMON_RADIO_CONFIG_H
#define COMMON_RADIO_CONFIG_H

#include <stdint.h>

// ===================== SLOT TIMING =====================

#define SLOT_DURATION_US  250'000UL

// ===================== SLOT TYPES =====================
// Values are fixed — do not renumber. Wire format and design docs reference them by value.

enum WindowMode : uint8_t {
  WIN_TELEM         = 0,   // rocket TX telemetry / base RX — hopped channel, telem modulation
  WIN_CMD           = 1,   // base TX commands / rocket RX — fixed command channel, cmd modulation
  WIN_OFF           = 2,   // radio standby — low-power cycle
  WIN_LR            = 3,   // rocket TX long-range — hopped channel, LR modulation (implicit header, always overruns)
  WIN_FINDME        = 4,   // long-preamble beacon for passive scan (not yet implemented)
  WIN_BACKHAUL      = 5,   // base relay backhaul (not yet implemented)
  WIN_MULTIPURPOSE  = 6,   // future: multi-function cycle
  WIN_RDF           = 7,   // future: radio direction finding
  WIN_GFSK          = 8,   // future: GFSK high-rate telemetry
  WIN_CONTINUE      = 9,   // explicit no-op: extends previous slot, no radio action taken
  WIN_NARROWBAND_TELEM = 10,
  WIN_WIDEBAND_TELEM   = 11,
};

// ===================== SLOT SEQUENCE =====================
// Multiple sequences are planned (power-save, bench-test, etc).
// The active sequence must be agreed between rocket and base station.
// Length must be ≤16 (4-bit wire field in 0xAF stateFlags holds slot_index % SLOT_SEQUENCE_LEN).
// Length must be coprime with NUM_HOP_CHANNELS (23) for full channel coverage.
// Length 12 and 23 are coprime (gcd=1): full coverage every 276 slots ≈ 69 seconds.

static const WindowMode SLOT_SEQUENCE[] = {
  WIN_LR, WIN_CONTINUE, WIN_TELEM, WIN_TELEM,
  WIN_CMD, WIN_TELEM, WIN_TELEM, WIN_TELEM,
  WIN_TELEM, WIN_TELEM, WIN_TELEM, WIN_TELEM
};
#define SLOT_SEQUENCE_LEN  (sizeof(SLOT_SEQUENCE) / sizeof(SLOT_SEQUENCE[0]))

// ===================== FREQUENCY HOPPING =====================
// 23 channels from the AU915 BW125 band (channels 0–63: 915.2 + ch*0.2 MHz).
// Sequence generated by Fisher-Yates shuffle of channels 0–63, seed below.
// Command channel is excluded post-shuffle: if it appears in the first 23 entries,
// it is swapped with entry [23] so that changing the command channel only perturbs
// one position in the sequence rather than reshuffling everything.
// The sequence is regenerated at runtime (rederiveHopSequence()) when command channel changes.

#define NUM_HOP_CHANNELS  23

// Seed for Fisher-Yates. Fixed; determines the base hop order (before command-channel exclusion).
static const uint8_t HOP_SEED[] = {
  0x69, 0x42, 0x06, 0x96, 0x6c, 0x04, 0xed, 0xbc,
  0x0e, 0x98, 0xb2, 0x50, 0x18, 0x33, 0xc9, 0xd3,
  0xdc, 0x2d, 0xda
};
#define HOP_SEED_LEN  (sizeof(HOP_SEED) / sizeof(HOP_SEED[0]))

// hopSeq[] is filled by rederiveHopSequence() at init and whenever the command channel changes.
// Declared extern so each firmware has its own copy but shares this header.
// Definition is in radio.cpp for each firmware.
extern uint8_t hopSeq[NUM_HOP_CHANNELS];

// Derive the hop sequence from HOP_SEED, excluding cmdChannel from the first NUM_HOP_CHANNELS.
// Must be called at init and whenever cmdChannel changes.
// Uses a simple seeded PRNG (LCG) driven by HOP_SEED bytes.
// Both firmwares must call this with the same cmdChannel to stay in sync.
inline void rederiveHopSequence(uint8_t cmdChannel) {
  // Step 1: fill full channel list (0–63 BW125 channels only)
  uint8_t pool[64];
  for (uint8_t i = 0; i < 64; i++) pool[i] = i;

  // Step 2: Fisher-Yates shuffle using seed bytes as randomness source.
  // Seed bytes are consumed cyclically. A simple LCG extends the seed for indices
  // beyond the seed length.
  uint32_t lcg = 0;
  for (uint8_t i = 0; i < HOP_SEED_LEN; i++) lcg = (lcg << 8) ^ HOP_SEED[i];

  for (uint8_t i = 63; i > 0; i--) {
    // Advance LCG: multiplier and increment from Numerical Recipes
    lcg = lcg * 1664525UL + 1013904223UL;
    uint8_t j = (uint8_t)(lcg >> 16) % (i + 1);
    uint8_t tmp = pool[i]; pool[i] = pool[j]; pool[j] = tmp;
  }
  // pool[0..63] is now shuffled. Take first NUM_HOP_CHANNELS+1 = 24 entries.

  // Step 3: if cmdChannel appears in pool[0..NUM_HOP_CHANNELS-1], swap with pool[NUM_HOP_CHANNELS].
  // This excludes it from the hopping sequence without affecting the rest of the order.
  bool found = false;
  for (uint8_t i = 0; i < NUM_HOP_CHANNELS; i++) {
    if (pool[i] == cmdChannel) {
      uint8_t tmp = pool[i];
      pool[i] = pool[NUM_HOP_CHANNELS];
      pool[NUM_HOP_CHANNELS] = tmp;
      found = true;
      break;
    }
  }
  (void)found;  // suppress unused warning if assertions disabled

  // Step 4: copy first NUM_HOP_CHANNELS entries into hopSeq.
  for (uint8_t i = 0; i < NUM_HOP_CHANNELS; i++) hopSeq[i] = pool[i];
}

// Returns the hop channel for a given slot index.
// Both firmwares must have called rederiveHopSequence() with the same cmdChannel first.
inline uint8_t hopChannel(uint32_t slotIndex) {
  return hopSeq[slotIndex % NUM_HOP_CHANNELS];
}

// ===================== CHANNEL FREQUENCY TABLE =====================
// Channel 0-63:  BW125kHz, 915.2 + ch*0.2 MHz
// Channel 64-71: BW500kHz, 915.9 + (ch-64)*1.6 MHz

static inline float channelToFreqMHz(uint8_t ch) {
  if (ch < 64) return 915.2f + ch * 0.2f;
  if (ch < 72) return 915.9f + (ch - 64) * 1.6f;
  return 0.0f;
}

static inline float channelToBwKHz(uint8_t ch) {
  return (ch < 64) ? 125.0f : 500.0f;
}

#endif // COMMON_RADIO_CONFIG_H
